export const CustomEventType = {
    BeforeCopied: 'BeforeCopied',
    UpdateHeader: 'UpdateHeader',
    AfterWebsocket: 'AfterWebsocket',
    AfterCopied: 'AfterCopied',
    BeforeDeleted: 'BeforeDeleted',
    AfterDeleted: 'AfterDeleted',
    Deactivated: 'Deactivated',
    BeforePasted: 'BeforePasted',
    AfterPasted: 'AfterPasted',
    BeforeCreated: 'BeforeCreated',
    AfterCreated: 'AfterCreated',
    BeforeEmptyRowCreated: 'BeforeEmptyRowCreated',
    AfterEmptyRowCreated: 'AfterEmptyRowCreated',
    BeforeCreatedList: 'BeforeCreatedList',
    AfterCreatedList: 'AfterCreatedList',
    Selected: 'Selected',
    RowFocusIn: 'RowFocusIn',
    RowFocusOut: 'RowFocusOut',
    RowMouseEnter: 'RowMouseEnter',
    RowMouseLeave: 'RowMouseLeave',
    OpenRef: 'OpenRef',
    BeforePatchUpdate: 'BeforePatchUpdate',
    ValidatePatchUpdate: 'ValidatePatchUpdate',
    BeforePatchCreate: 'BeforePatchCreate',
    AfterPatchUpdate: 'AfterPatchUpdate',
};

export const TypeEntityAction = {
    UpdateEntity: 1,
    UpdateCountBadge: 2,
    Message: 3,
    MessageCountBadge: 4,
};