export class ElementType {
    static get a() { return 'a'; }
    static get abbr() { return 'abbr'; }
    static get address() { return 'address'; }
    static get area() { return 'area'; }
    static get article() { return 'article'; }
    static get aside() { return 'aside'; }
    static get audio() { return 'audio'; }
    static get b() { return 'b'; }
    static get base() { return 'base'; }
    static get bdi() { return 'bdi'; }
    static get bdo() { return 'bdo'; }
    static get blockquote() { return 'blockquote'; }
    static get button() { return 'button'; }
    static get canvas() { return 'canvas'; }
    static get caption() { return 'caption'; }
    static get cite() { return 'cite'; }
    static get code() { return 'code'; }
    static get col() { return 'col'; }
    static get colgroup() { return 'colgroup'; }
    static get datalist() { return 'datalist'; }
    static get dd() { return 'dd'; }
    static get del() { return 'del'; }
    static get details() { return 'details'; }
    static get dfn() { return 'dfn'; }
    static get div() { return 'div'; }
    static get dl() { return 'dl'; }
    static get dt() { return 'dt'; }
    static get em() { return 'em'; }
    static get embed() { return 'embed'; }
    static get fieldset() { return 'fieldset'; }
    static get figcaption() { return 'figcaption'; }
    static get figure() { return 'figure'; }
    static get footer() { return 'footer'; }
    static get form() { return 'form'; }
    static get h1() { return 'h1'; }
    static get h2() { return 'h2'; }
    static get h3() { return 'h3'; }
    static get h4() { return 'h4'; }
    static get h5() { return 'h5'; }
    static get h6() { return 'h6'; }
    static get head() { return 'head'; }
    static get header() { return 'header'; }
    static get i() { return 'i'; }
    static get iframe() { return 'iframe'; }
    static get img() { return 'img'; }
    static get input() { return 'input'; }
    static get ins() { return 'ins'; }
    static get kbd() { return 'kbd'; }
    static get keygen() { return 'keygen'; }
    static get label() { return 'label'; }
    static get legend() { return 'legend'; }
    static get li() { return 'li'; }
    static get link() { return 'link'; }
    static get main() { return 'main'; }
    static get map() { return 'map'; }
    static get mark() { return 'mark'; }
    static get menu() { return 'menu'; }
    static get menuitem() { return 'menuitem'; }
    static get meta() { return 'meta'; }
    static get meter() { return 'meter'; }
    static get nav() { return 'nav'; }
    static get object() { return 'object'; }
    static get ol() { return 'ol'; }
    static get optgroup() { return 'optgroup'; }
    static get option() { return 'option'; }
    static get output() { return 'output'; }
    static get p() { return 'p'; }
    static get param() { return 'param'; }
    static get pre() { return 'pre'; }
    static get progress() { return 'progress'; }
    static get q() { return 'q'; }
    static get rp() { return 'rp'; }
    static get rt() { return 'rt'; }
    static get ruby() { return 'ruby'; }
    static get s() { return 's'; }
    static get samp() { return 'samp'; }
    static get script() { return 'script'; }
    static get section() { return 'section'; }
    static get select() { return 'select'; }
    static get small() { return 'small'; }
    static get source() { return 'source'; }
    static get span() { return 'span'; }
    static get strong() { return 'strong'; }
    static get style() { return 'style'; }
    static get sub() { return 'sub'; }
    static get summary() { return 'summary'; }
    static get sup() { return 'sup'; }
    static get table() { return 'table'; }
    static get tbody() { return 'tbody'; }
    static get td() { return 'td'; }
    static get textarea() { return 'textarea'; }
    static get tfoot() { return 'tfoot'; }
    static get th() { return 'th'; }
    static get thead() { return 'thead'; }
    static get time() { return 'time'; }
    static get title() { return 'title'; }
    static get tr() { return 'tr'; }
    static get track() { return 'track'; }
    static get u() { return 'u'; }
    static get ul() { return 'ul'; }
    static get var() { return 'var'; }
    static get video() { return 'video'; }
}
